### ISSUE TITLE
Possible Unhandled Promise: null is not an object

### ISSUE THREAD

**Issue by kashmiry** [osamaq/react-native-image-colors#3]
I am trying to use the package for the first time testing with the same sample code:
```
 async function imageToColors(imageUrl){
        const colors = await ImageColors.getColors(imageUrl, {
            average: true,
            defaultColor: "#000000"
        });

        if (colors.platform === "android") {
        // Access android properties
        // e.g.
        const averageColor = colors.average;
        } else {
        // Access iOS properties
        // e.g.
        const backgroundColor = colors.background;
        }
        console.log('====================================');
        console.log(colors);
        console.log('====================================');
    }
```

I get this error, when I run the function.
`Possible Unhandled Promise Rejection (id: 18):
TypeError: null is not an object (evaluating '_reactNativeImageColors.default.getColors')`

**Comment by osamaq** [comment]
Hey. May I know what steps you took to run the example project? I just tried the following and it worked for me on both iOS and Android:

1- Clone the repo

```
$ git clone https://github.com/osamaq/react-native-image-colors.git
```

2- Install example project dependencies

```
$ cd react-native-image-colors\example

$ yarn 
or
$ npm i
```

3- Pod dependencies, iOS only:

```
npx pod-install
```

4- Run the app

```
$ yarn run android
or
$ yarn run ios
```

**Comment by osamaq** [comment]
I have also tested with a brand new project using `react-native init ...`
The same steps should work. Please double check that you have followed similar steps.

If you did, and it still doens't work, please let me know.

**Comment by kashmiry** [comment]
I am testing it on my application, not on fresh react-native.
Currently I tried to remove it and install again. and I got an error on the build:
- Undefined symbol: _swift_getFunctionReplacement
- Undefined symbol: _swift_getOrigOfReplaceable

I tried many things like:
- Creating a dummy swit file.
- Set `Strip Debug Symbols During Copy` to True
- Set `Always Embed Swift Standard Libraries` to True
- Following [React Native 0.62 upgrade(Xcode)](https://github.com/react-native-community/upgrade-support/issues/13) guide.
- Clean bulid.
-`pod repo update`

If I remove the package everything works fine. not sure what's wrong really. I'll keep looking..

more error details:
```
Undefined symbols for architecture x86_64:
  "_swift_getFunctionReplacement", referenced from:
      _swift_getFunctionReplacement50 in libswiftCompatibilityDynamicReplacements.a(DynamicReplaceable.cpp.o)
     (maybe you meant: _swift_getFunctionReplacement50)
  "_swift_getOrigOfReplaceable", referenced from:
      _swift_getOrigOfReplaceable50 in libswiftCompatibilityDynamicReplacements.a(DynamicReplaceable.cpp.o)
     (maybe you meant: _swift_getOrigOfReplaceable50)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by osamaq** [comment]
The upgrade to 0.62 was a very buggy experience with regards to Swift compilation for me as well. Can you afford to create a new +0.62 project and copy your files to it? I don't know how big is your project, but this could be the fastest solution.

**Comment by osamaq** [comment]
Hi. I was able to to create a new RN0.60 project which has no Swift support and got it to work by following the 3 steps [here](https://github.com/facebook/flipper/blob/4297b3061f14ceca4d184aa3eebd0731b5bf20f5/docs/getting-started.md#for-pure-objective-c-projects).

Here is the project:
https://github.com/osamaq/react-native-image-colors-rn0.60

**Comment by kashmiry** [comment]
@osamaq Tried it, but still no luck. I will plan a clean install in the future or a roll back.
Thank you for your help. and for the great module 🙏🏼
