### ISSUE TITLE
Is there any way I can pass in an Image blob?

### ISSUE THREAD

**Issue by JoeyFenny** [osamaq/react-native-image-colors#4]
Is there any way I can pass in an Image blob as the source instead of a url?

I get error "could not download image"

**Comment by osamaq** [comment]
Hey. Currently it only supports URLs. That's the error you're seeing.
Might take a look into extending the API this weekend.

**Comment by osamaq** [comment]
Not sure this is your exact use case, but with version `1.2.0` you can now pass local image files that you load with `require(...)`.

https://github.com/osamaq/react-native-image-colors#example

**Comment by osamaq** [comment]
Closing due to no response.
