### ISSUE TITLE
iOS - Module not able to Download file from Camera roll path e.g ph://19816598-0009-4C6B-BE19-2939E73737E8/L0/001

### ISSUE THREAD

**Issue by joypatel04** [osamaq/react-native-image-colors#5]
URI = `ph://19816598-0009-4C6B-BE19-2939E73737E8/L0/001`

local storage URI doesn't download the image.

```
const getColors = async (uri) => {
    try {
      const colors = await ImageColors.getColors(uri, {
        fallback: '#fff',
      });
      return Platform.OS === 'ios' ? colors.background :  colors.lightMuted;
    } catch (e) {
      console.log(e);
    }
  };
```

Error:
```
Error: Could not download image.
    at Object.promiseMethodWrapper [as getColors] (NativeModules.js:103)
    at Object.getColors (index.js:8)
    at getColors$ (index.js:40)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:189
    at tryCallTwo (core.js:45)
```

Please help @osamaq

**Comment by osamaq** [comment]
The file path looks weird. It should be `file://...`. Googling tells me it's a common issue when importing an image from the camera roll.

If I'm correct, could you try:
 https://github.com/react-native-community/react-native-video/issues/1572#issuecomment-489347591

Or
 https://github.com/pentarex/react-native-gallery-manager

**Comment by osamaq** [comment]
Closing due to no follow up.

**Comment by alexkendall** [comment]
I have the same issue. Even converted to base64 beforehand, and get the error `Error: Could not download image.`

**Comment by pyc92** [comment]
save issue
